//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusikMacher.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusikMacher.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add Tag.
        /// </summary>
        public static string AddTag {
            get {
                return ResourceManager.GetString("AddTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caching Waveforms.
        /// </summary>
        public static string CachingWaveforms {
            get {
                return ResourceManager.GetString("CachingWaveforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check for update.
        /// </summary>
        public static string CheckForUpdate {
            get {
                return ResourceManager.GetString("CheckForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add comment.
        /// </summary>
        public static string CommentAdd {
            get {
                return ResourceManager.GetString("CommentAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Playback.
        /// </summary>
        public static string ContinuePlayback {
            get {
                return ResourceManager.GetString("ContinuePlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically play the next track once the current one ends. When enabled, this feature emulates standard music player behavior..
        /// </summary>
        public static string ContinuePlaybackDescription {
            get {
                return ResourceManager.GetString("ContinuePlaybackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop playback.
        /// </summary>
        public static string ContinuePlaybackFalse {
            get {
                return ResourceManager.GetString("ContinuePlaybackFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continue playback.
        /// </summary>
        public static string ContinuePlaybackTrue {
            get {
                return ResourceManager.GetString("ContinuePlaybackTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy as path.
        /// </summary>
        public static string CopyAsPath {
            get {
                return ResourceManager.GetString("CopyAsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy as File.
        /// </summary>
        public static string CopyFile {
            get {
                return ResourceManager.GetString("CopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy name.
        /// </summary>
        public static string CopyName {
            get {
                return ResourceManager.GetString("CopyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation time.
        /// </summary>
        public static string CreationTime {
            get {
                return ResourceManager.GetString("CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DownloadPost {
            get {
                return ResourceManager.GetString("DownloadPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download .
        /// </summary>
        public static string DownloadPre {
            get {
                return ResourceManager.GetString("DownloadPre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effects.
        /// </summary>
        public static string Effects {
            get {
                return ResourceManager.GetString("Effects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred: {0}.
        /// </summary>
        public static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated time left.
        /// </summary>
        public static string EstimatedTimeLeft {
            get {
                return ResourceManager.GetString("EstimatedTimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load from {0}: Directory does not exists..
        /// </summary>
        public static string FailedSubsection {
            get {
                return ResourceManager.GetString("FailedSubsection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve release information. Status code: {0}.
        /// </summary>
        public static string FailedToRetrieve {
            get {
                return ResourceManager.GetString("FailedToRetrieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        public static string Favorite {
            get {
                return ResourceManager.GetString("Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find in songs (Ctrl + F).
        /// </summary>
        public static string FindInSongs {
            get {
                return ResourceManager.GetString("FindInSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find in tags (Ctrl + T).
        /// </summary>
        public static string FindInTags {
            get {
                return ResourceManager.GetString("FindInTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixes.
        /// </summary>
        public static string Fixes {
            get {
                return ResourceManager.GetString("Fixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide track.
        /// </summary>
        public static string HideTrack {
            get {
                return ResourceManager.GetString("HideTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done..
        /// </summary>
        public static string ImportDone {
            get {
                return ResourceManager.GetString("ImportDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import into.
        /// </summary>
        public static string ImportInto {
            get {
                return ResourceManager.GetString("ImportInto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import subfolders.
        /// </summary>
        public static string ImportSubfolders {
            get {
                return ResourceManager.GetString("ImportSubfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display language of the user interface..
        /// </summary>
        public static string LanguageDescription {
            get {
                return ResourceManager.GetString("LanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last checked:.
        /// </summary>
        public static string LastChecked {
            get {
                return ResourceManager.GetString("LastChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load cover art.
        /// </summary>
        public static string LoadCovers {
            get {
                return ResourceManager.GetString("LoadCovers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the application crashes often it might help to disable cover loading.
        /// </summary>
        public static string LoadCoversDescription {
            get {
                return ResourceManager.GetString("LoadCoversDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no cover art.
        /// </summary>
        public static string LoadCoversFalse {
            get {
                return ResourceManager.GetString("LoadCoversFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to load cover art.
        /// </summary>
        public static string LoadCoversTrue {
            get {
                return ResourceManager.GetString("LoadCoversTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load data.
        /// </summary>
        public static string LoadData {
            get {
                return ResourceManager.GetString("LoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} known songs and created {1}new ones in database.
        /// </summary>
        public static string LoadedSuccessfulSubsection {
            get {
                return ResourceManager.GetString("LoadedSuccessfulSubsection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to load data from `{0}`.
        /// </summary>
        public static string LoadingDataFrom {
            get {
                return ResourceManager.GetString("LoadingDataFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading from subfolder {0}.
        /// </summary>
        public static string LoadingDataFromSublocation {
            get {
                return ResourceManager.GetString("LoadingDataFromSublocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never checked.
        /// </summary>
        public static string NeverChecked {
            get {
                return ResourceManager.GetString("NeverChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version is available ({0}), you have {1}.
        /// </summary>
        public static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No songs found..
        /// </summary>
        public static string NoSongsFound {
            get {
                return ResourceManager.GetString("NoSongsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one.
        /// </summary>
        public static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Log.
        /// </summary>
        public static string OpenConsole {
            get {
                return ResourceManager.GetString("OpenConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To debug the application it might be helpful to open the console to view the log output in realtime. Requires programm restart to open console..
        /// </summary>
        public static string OpenConsoleDescription {
            get {
                return ResourceManager.GetString("OpenConsoleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to search.
        /// </summary>
        public static string PathToSearch {
            get {
                return ResourceManager.GetString("PathToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause (Space).
        /// </summary>
        public static string PauseTooltip {
            get {
                return ResourceManager.GetString("PauseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Effects from Start.
        /// </summary>
        public static string PlayEffectsFromStart {
            get {
                return ResourceManager.GetString("PlayEffectsFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure playback in the effects tab always begins from the start..
        /// </summary>
        public static string PlayEffectsFromStartDescription {
            get {
                return ResourceManager.GetString("PlayEffectsFromStartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play from playback position.
        /// </summary>
        public static string PlayEffectsFromStartFalse {
            get {
                return ResourceManager.GetString("PlayEffectsFromStartFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play from start.
        /// </summary>
        public static string PlayEffectsFromStartTrue {
            get {
                return ResourceManager.GetString("PlayEffectsFromStartTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play (Space).
        /// </summary>
        public static string PlayTooltip {
            get {
                return ResourceManager.GetString("PlayTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preload all Waveforms.
        /// </summary>
        public static string PreloadAllWaveforms {
            get {
                return ResourceManager.GetString("PreloadAllWaveforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premiere.
        /// </summary>
        public static string Premiere {
            get {
                return ResourceManager.GetString("Premiere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset search.
        /// </summary>
        public static string ResetSearch {
            get {
                return ResourceManager.GetString("ResetSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset tags.
        /// </summary>
        public static string ResetTags {
            get {
                return ResourceManager.GetString("ResetTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apperance.
        /// </summary>
        public static string SettingsApperance {
            get {
                return ResourceManager.GetString("SettingsApperance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback.
        /// </summary>
        public static string SettingsPlayback {
            get {
                return ResourceManager.GetString("SettingsPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string SettingsTags {
            get {
                return ResourceManager.GetString("SettingsTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version &amp;amp; updates.
        /// </summary>
        public static string SettingsVersionAndUpdates {
            get {
                return ResourceManager.GetString("SettingsVersionAndUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show hidden tags.
        /// </summary>
        public static string ShowHiddenTagsTooltip {
            get {
                return ResourceManager.GetString("ShowHiddenTagsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show hidden tracks.
        /// </summary>
        public static string ShowHiddenTooltip {
            get {
                return ResourceManager.GetString("ShowHiddenTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip back (Left Arrow).
        /// </summary>
        public static string SkipBackTooltip {
            get {
                return ResourceManager.GetString("SkipBackTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip back the track about the configured time. (see Settings to change amount).
        /// </summary>
        public static string SkipBackTooltipDescription {
            get {
                return ResourceManager.GetString("SkipBackTooltipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip forward (Right Arrow).
        /// </summary>
        public static string SkipForwardTooltip {
            get {
                return ResourceManager.GetString("SkipForwardTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip forward the track about the configured time. (see Settings to change amount).
        /// </summary>
        public static string SkipForwardTooltipDescription {
            get {
                return ResourceManager.GetString("SkipForwardTooltipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Percentage.
        /// </summary>
        public static string SkipPercentage {
            get {
                return ResourceManager.GetString("SkipPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust the percentage of the track to skip when pressing the left/right arrow buttons.
        /// </summary>
        public static string SkipPercentageDescription {
            get {
                return ResourceManager.GetString("SkipPercentageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs.
        /// </summary>
        public static string Songs {
            get {
                return ResourceManager.GetString("Songs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Playback Position.
        /// </summary>
        public static string StartPlaybackPosition {
            get {
                return ResourceManager.GetString("StartPlaybackPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the starting position within the song for playback to begin.
        /// </summary>
        public static string StartPlaybackPositionDescription {
            get {
                return ResourceManager.GetString("StartPlaybackPositionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Filter.
        /// </summary>
        public static string TagFilter {
            get {
                return ResourceManager.GetString("TagFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose how tracks are filtered: either they must have just one selected tags or all of them..
        /// </summary>
        public static string TagFilterDescription {
            get {
                return ResourceManager.GetString("TagFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try without tags or search?.
        /// </summary>
        public static string TryWithoutTagsOrSearch {
            get {
                return ResourceManager.GetString("TryWithoutTagsOrSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhide track.
        /// </summary>
        public static string UnhideTrack {
            get {
                return ResourceManager.GetString("UnhideTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musik Macher is up to date.
        /// </summary>
        public static string UpToDate {
            get {
                return ResourceManager.GetString("UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Title.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalize the title of the window. For example, you could promote subscribing with Twitch Prime or mention the !macher command..
        /// </summary>
        public static string WindowTitleDescription {
            get {
                return ResourceManager.GetString("WindowTitleDescription", resourceCulture);
            }
        }
    }
}
